services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver-data:/var/opt/mssql

  gaussianexplorer.api:
    image: romanc647/gaussianexplorerapi:latest
    container_name: api
    build:
      context: .
      dockerfile: Web.API/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
    depends_on:
      - sqlserver

volumes:
  sqlserver-data: