services:
  sqlserver:
    environment:
      - SA_PASSWORD=dev_a*9UiZx*NVkbwe@9
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$${SA_PASSWORD}" -Q "SELECT 1"
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  gaussianexplorer.api:
    image: romanc647/gaussianexplorerapi:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/home/app/.aspnet/https/GaussianExplorer.API.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=api_dev
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      sqlserver:
        condition: service_healthy
