name: Docker Build and Push - Development

on:
  push:
    branches:
      - development
    paths:
      - 'gaussian-explorer-api/**'
  pull_request:
    branches:
      - development
    paths:
      - 'gaussian-explorer-api/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: development
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./API/Dockerfile
          push: true
          tags: |
            romanc647/gaussianexplorerapi:dev
            romanc647/gaussianexplorerapi:dev-${{ github.sha }}
          cache-from: type=registry,ref=romanc647/gaussianexplorerapi:buildcache-dev
          cache-to: type=registry,ref=romanc647/gaussianexplorerapi:buildcache-dev,mode=max